/**
 * @file Unit tests for problem12.js
 * @author Thomas J. Purk
 * The sequence of triangle numbers is generated by adding the natural numbers.
 * So the 7th triangle number would be 1+2+3+4+5+6+7=28.
 * The first ten terms would be:
 * 1,3,6,10,15,21,28,36,45,55,…
 * Let us list the factors of the first seven triangle numbers:
 *       1: 1
 *       3: 1,3
 *       6: 1,2,3,6
 *      10: 1,2,5,10
 *      15: 1,3,5,15
 *      21: 1,3,7,21
 *      28: 1,2,4,7,14,28
 * We can see that 28 is the first triangle number to have over five divisors.
 * What is the value of the first triangle number to have over five hundred divisors?
 */
import { it, expect, describe } from "vitest";
import { problem12 } from "./problem12.js";

describe("problem12()", () => {
  it("sould return the correct answer to the sample problem", () => {
    // Arrange
    const input = 5;
    const expectedResult = 28;
    // Act
    const result = problem12(input);
    // Assert
    expect(result).toEqual(expectedResult);
  });
});
